require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

  Exclude:
    - 'bin/*'
    - 'vendor/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 18

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/SymbolArray:
  Enabled: true

RSpec/NestedGroups:
  Max: 5

Style/AccessorGrouping:
  EnforcedStyle: separated
